---
- name: Base playbook
  become: true
  gather_facts: yes
  hosts: all
  tasks:
  - name: Running react role
    import_role:
      name: react
    when: "ansible_default_ipv4.address == '10.0.0.2'"
  - name: Running graphql role
    import_role:
      name: graphql
    when: "ansible_default_ipv4.address == '10.0.0.5'"