---
- name: Installing Packages
  package:
    name: "{{ packages }}"
    state: present
- name: Installing Global Node Packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop: "{{ npm_packages }}"
- name: Ensuring /var/www Exists
  file:
    path: /var/www
    state: directory
    mode: '0775'
    owner: nginx
    group: nginx
- name: Setting Safe Directories in Git Config
  community.general.git_config:
    name: safe.directory
    scope: global
    value: /var/www/bbqguys-frontend
- name: Cloning bbqguys-frontend React Repository
  git:
    repo: git@github.com:BBQGuys-QA/bbqguys-frontend.git
    dest: /var/www/bbqguys-frontend
    accept_hostkey: true
    single_branch: true
    depth: 1
    force: true
    version: testing
    key_file: /home/shardy/.ssh/id_rsa # This should be changed to a generic system user later.
- name: Placing .env
  copy:
    src: var/www/bbqguys-frontend/.env
    dest: /var/www/bbqguys-frontend/.env
    owner: nginx
    group: nginx
    mode: '0644'
#- name: Placing .env File
#  copy:
#    src: /var/www/bbqguys-frontend/.env.testing
#    dest: /var/www/bbqguys-frontend/.env
#    remote_src: yes
#    local_follow: false
#    force: true
#    owner: nginx
#    group: nginx
#    mode: '0644'
- name: Placing pm2.config.js
  copy:
    src: var/www/bbqguys-frontend/pm2.config.js
    dest: /var/www/bbqguys-frontend/pm2.config.js
    owner: nginx
    group: nginx
    mode: '0644'
- name: Installing Yarn Packages
  command:
    chdir: /var/www/bbqguys-frontend
    cmd: /usr/bin/yarn install --ignore-engines
- name: Building bundle
  command:
    chdir: /var/www/bbqguys-frontend
    cmd: /usr/bin/yarn testing:build-bundle
- name: Building server
  command:
    chdir: /var/www/bbqguys-frontend
    cmd: /usr/bin/yarn testing:build-server
- name: Updating owner and group of /var/www/bbqguys-frontend
  file:
    path: /var/www/bbqguys-frontend
    owner: nginx
    group: nginx
    recurse: true
- name: Ensuring /etc/nginx/ssl exists
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0644'
    owner: root
    group: root
- name: Installing TLS cert
  copy:
    src: etc/nginx/ssl/ssl.pem
    dest: /etc/nginx/ssl/ssl.pem
    owner: root
    group: root
    mode: '0644'
- name: Installing TLS key
  copy:
    src: etc/nginx/ssl/ssl.key
    dest: /etc/nginx/ssl/ssl.key
    owner: root
    group: root
    mode: '0644'
- name: Updating nginx configuration
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
- name: Starting nginx
  service:
    name: nginx
    enabled: true
    state: restarted
- name: Checking if PM2 is Running for Nginx User
  command: pgrep -u nginx PM2
  register: pm2_status
  ignore_errors: true
- name: pm2_status debug
  debug:
    msg: pm2_status is {{ pm2_status }}
- name: Stopping existing PM2
  become: yes
  become_user: nginx
  command:
    cmd: /usr/bin/pm2 kill
  when: pm2_status.rc == 0
- name: Starting bbqguys-frontend
  become: yes
  become_user: nginx
  command:
    chdir: /var/www/bbqguys-frontend
    cmd: /usr/bin/pm2 start /var/www/bbqguys-frontend/pm2.config.js --env testing
  register: pm2_start_result
- name: Debug pm2 start
  debug:
    msg: '{{ pm2_start_result }}'
