---
- name: Upgrading all packages
  package:
    name: "*"
    state: latest
- name: Non-Prod Setup
  block:
    - name: Install non-prod packages
      package:
        name: "{{ non_prod_packages }}"
        state: present
    - name: Installing MailHog
      shell: |
        go get -u github.com/mailhog/MailHog
        mv ~/go/bin/MailHog /usr/local/bin/
    - name: Place MailHog Service File
      copy:
        src: etc/systemd/system/mailhog.service
        dest: /etc/systemd/system/mailhog.service
        owner: root
        group: root
        mode: '0755'
    - name: Ensure MailHog Log Directory Exists
      file:
        path: /var/log/mailhog
        state: directory
        mode: '0775'
        owner: root
        group: root
    - name: Start MailHog Service
      service:
        name: mailhog
        state: started
        enabled: yes
  when: non_prod is true
- name: Get node version
  shell: node --version
  register: node_installed_version
  ignore_errors: true
- name: Print node_installed_version
  debug:
    msg: "{{ node_installed_version }}"
- name: Downloading and Unpacking NodeJS Version
  unarchive: 
    src: "https://nodejs.org/download/release/{{ node_version }}/{{ node_directory }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes
  when: (node_installed_version.stdout != node_version) or (node_installed_version is undefined)
- name: Installing NodeJS From Extracted Package
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    local_follow: false
    force: true
  loop:
    - src: "/tmp/{{ node_directory }}/bin"
      dest: /usr/
    - src: "/tmp/{{ node_directory }}/include"
      dest: /usr/
    - src: "/tmp/{{ node_directory }}/lib"
      dest: /usr/
    - src: "/tmp/{{ node_directory }}/share"
      dest: /usr/
- name: Configuring Nginx group
  group:
    name: nginx
- name: Configuring Nginx User
  user:
    name: nginx
    comment: nginx
    group: nginx
    system: true